name: agent-lite

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Describe the next small task (optional; defaults to ROADMAP.md first unchecked item)"
        required: false
        type: string
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # set author before any commits happen
      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm (global)
        run: npm i -g pnpm@9.12.0

      - name: Verify pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Doctor
        run: pnpm -s agent:doctor || { echo "doctor failed (stub or actionable)"; exit 1; }

      - name: Build context
        run: pnpm agent:context

      - name: Plan step
        run: pnpm agent:plan
        env:
          AGENT_TASK: ${{ github.event.inputs.task }}

      # optional LLM generation of .agent/ops.json (falls back if no key)
      - name: Generate ops (LLM; optional)
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5
          AGENT_TASK: ${{ github.event.inputs.task }}
        run: pnpm -s agent:gen-ops || echo "ops generation skipped"

      # upload ops.json as an artifact if present
      - name: Upload ops.json artifact (if present)
        if: ${{ hashFiles('.agent/ops.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: agent-ops-json
          path: .agent/ops.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Implement step (branch + apply ops or seed)
        run: pnpm agent:impl

      - name: Run checks (typecheck, lint, unit tests)
        run: pnpm agent:check

      - name: Get branch name
        id: br
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"

      - name: Push branch
        if: ${{ success() }}
        run: git push --set-upstream origin "${{ steps.br.outputs.branch }}"

      - name: Read plan meta
        if: ${{ success() }}
        id: planmeta
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = JSON.parse(fs.readFileSync('.agent/plan.json','utf8'));
            core.setOutput('id', plan.chosen.id);
            core.setOutput('title', plan.chosen.title);

      - name: Create Pull Request
        if: ${{ success() }}
        id: create-pr
        uses: actions/github-script@v7
        env:
          BRANCH: ${{ steps.br.outputs.branch }}
          TITLE: ${{ steps.planmeta.outputs.title }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = process.env.BRANCH;
            const base = 'main';
            const title = `Agent Lite: ${process.env.TITLE || head}`;
            const body = 'Automated agent step (plan/implement/check). Review carefully.';

            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`,
            });
            if (prs.length) {
              core.setOutput('url', prs[0].html_url);
            } else {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, head, base, title, body
              });
              core.setOutput('url', pr.html_url);
            }

      - name: PR link
        if: ${{ success() }}
        run: echo "PR opened:${{ steps.create-pr.outputs.url }}"

  check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm (global)
        run: npm i -g pnpm@9.12.0
      - name: Verify pnpm
        run: pnpm --version
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Agent check (typecheck + lint(agent) + build context + unit tests + validate)
        run: pnpm agent:check

      # publish a stable commit status so Branch Protection can see/select it
      - name: Publish status (success)
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request?.head?.sha || context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'success',
              context: 'agent-lite / check',
              description: 'Checks passed'
            });

      - name: Publish status (failure)
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request?.head?.sha || context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'failure',
              context: 'agent-lite / check',
              description: 'Checks failed'
            });
