name: agent-lite

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Describe the next small task (optional; defaults to ROADMAP.md first unchecked item)"
        required: false
        type: string
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 9
        run: corepack prepare pnpm@9.12.0 --activate

      - name: Verify pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build context
        run: pnpm agent:context

      - name: Plan step
        run: pnpm agent:plan
        env:
          AGENT_TASK: ${{ github.event.inputs.task }}

      - name: Implement step (branch + seed)
        run: pnpm agent:impl

      - name: Run checks (typecheck, lint, unit tests)
        run: pnpm agent:check

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get branch name
        id: br
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"

      - name: Push branch
        run: git push --set-upstream origin "${{ steps.br.outputs.branch }}"

      - name: Create Pull Request
        id: create-pr
        uses: actions/github-script@v7
        env:
          BRANCH: ${{ steps.br.outputs.branch }}
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = process.env.BRANCH;
            const base = 'main';
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`,
            });
            if (prs.length) {
              core.setOutput('url', prs[0].html_url);
            } else {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, head, base,
                title: `agent: ${head}`,
                body: 'Automated agent step (plan/implement/check). Review carefully.',
              });
              core.setOutput('url', pr.html_url);
            }

      - name: PR link
        run: echo "PR opened:${{ steps.create-pr.outputs.url }}"

  check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 9
        run: corepack prepare pnpm@9.12.0 --activate

      - name: Verify pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Agent check (typecheck + lint(agent) + build context + unit tests + validate)
        run: pnpm agent:check
